/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttributeControl: typeof import('./src/components/AttributeControl.vue')['default']
    'Base.ids': typeof import('./src/components/doc/traces/base.ids.vue')['default']
    BaseIds: typeof import('./src/components/doc/traces/BaseIds.vue')['default']
    BaseX0: typeof import('./src/components/doc/traces/BaseX0.vue')['default']
    BasicAside: typeof import('./src/components/BasicAside.vue')['default']
    CodeAndPlot: typeof import('./src/components/CodeAndPlot.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    DataRevision: typeof import('./src/components/doc/layout/DataRevision.vue')['default']
    EditRevision: typeof import('./src/components/doc/layout/EditRevision.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    GirdSubplot: typeof import('./src/components/doc/layout/GirdSubplot.vue')['default']
    GirdXaxes: typeof import('./src/components/doc/layout/GirdXaxes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionRevision: typeof import('./src/components/doc/layout/SelectionRevision.vue')['default']
    Template: typeof import('./src/components/doc/layout/Template.vue')['default']
    TraceData: typeof import('./src/components/doc/TraceData.vue')['default']
    UiRevision: typeof import('./src/components/doc/layout/UiRevision.vue')['default']
  }
}
